version: '3.8'

services:
  backend:
    build: ./backend
    container_name: engineering-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: engineering-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
